### PR TITLE
Transfer outputs of salmon_align to count Matrix

### PR DESCRIPTION
**Pull request by chlu0571**
- [x] Test in command-line for gtfToGenePred to produce Tx2gene file
- [x] Created Tx2gene file with gtfToGenePred (makeTx2geneFile.nf)
- [x] Consulted [nf-core/rnaseq] (https://github.com/nf-core/rnaseq) for tximport.r and stored it in /bin
- [x] Modified the nextflow script from [nf-core/rnaseq] (https://github.com/nf-core/rnaseq)
- [x] Modified the main.nf to include extra modules
- [x] Changed and grouped the output parameters in RunSalmonAlign
- [x] Created MergeSalmonCount to merge all counts from Tximport
- [x] Print out headers according to each sample in merge count file
- [x] Test and run successfully. 

Pca requires more samples. 
``
executor >  local (25)
[52/d4dea2] process > checkCohort (1)                                                                       [100%] 1 of 1 ✔

[6e/3ccb81] process > fastqc (UHR_Rep2 fastQC)                                                        [100%] 3 of 3 ✔

[e1/8744cf] process > bbduk (1)                                                                                   [100%] 3 of 3 ✔

[da/f3b4a8] process > makeSTARIndex                                                                        [100%] 1 of 1 ✔

[7a/cba092] process > runSTARAlign (UHR_Rep3 runSTARAlign)                                 [100%] 3 of 3 ✔

[b0/c72a33] process > runSamtoolsMergeIndex (runSamtoolsMergeIndex)               [100%] 2 of 2 ✔

[f2/33a55c] process > runHtseqCount (UHR_Rep2 runHtseqCount)                            [100%] 2 of 2 ✔

[9c/de1cbb] process > mergeHtseqCounts (null runSTARAlign)                                  [100%] 1 of 1 ✔

[92/7e3bd5] process > makeSalmonIndex                                                                   [100%] 1 of 1 ✔

[82/68ceca] process > runSalmonAlign (1)                                                                   [100%] 2 of 2 ✔

[d7/3074a6] process > makeTx2geneFile                                                                      [100%] 1 of 1 ✔

[dc/058226] process > runTximportCount (1)                                                               [100%] 2 of 2 ✔

[fb/821fbe] process > mergeSalmonCounts                                                                 [100%] 1 of 1 ✔

[1c/1a8a04] process > createPCAFromCounts (createPCAFromCounts)                      [100%] 1 of 1, failed: 1 ✘

[04/6b5712] process > convertGtfToBED (convertGtfToBED)                                        [100%] 1 of 1 ✔

``

### CODE REVIEW

**Review by nandan75 — CHANGES_REQUESTED** [review]
samtoolsMergeInput = runSTARAlign.out.sample_lane_bam
  //.view() //ADDED THIS TO VISUALISE OUT STRUCTURE FOR DEBUGGING PURPOSES
  .map { tuple ->
  // Extracting values and paths from the tuple produced by runSTARAlign.out.sample_lane_bam
  def sampleID = tuple[0]
  def path_bam = tuple[1]
  def path_SJ = tuple[2]
 
You don't want to
 
1) Dependant on STAR alignment for anything to do with salmon alignment -- As There is a high possibility that we will allow the user to do either / or or both the alignment
2) For the same reason, You should not be waiting for output of runSTARAlign to create a tuple for salmon!
3) I think you should take it from align_input.out ..
 
Also
 
Can you  run the pipeline (maybe NOT STAR steps) but rest of it for 
samples=/scratch/er01/ndes8648/pipeline_work/nextflow/INFRA-121-RNASeq-DE/RNAseq-DE-nf/sampleSheet_all_paired.csv
 So that you can confirm that the salmon steps creates a final file compatible with salmon matrix
 Also
 
4) At this time, you are not passing the "merged_counts_Salmon.tsv" from mergeSalmonCounts.nf to the createPCAFromCounts and then adding a line of code to create the salmonPCA (remember to // the STAR PCA line for now)

**Comment by chlu0571** [comment]
I think the input for salmon is different to STAR. SalmonAlign used "alignmentInputSalmon = align_input.groupTuple()". But Yes, I will try to feed the PCA with mergeSalmonCounts.

**Comment by nandan75** [comment]
> I think the input for salmon is different to STAR. SalmonAlign used "alignmentInputSalmon = align_input.groupTuple()". But Yes, I will try to feed the PCA with mergeSalmonCounts.

True, You are correct :-) I misread the code. No changes to Salmon input

Do let me know when the salmon matrix is put as an additional input to the PCA process and once you are done testing.
Cheers.

**Review by nandan75 — APPROVED** [review]
- tested all steps - run as expected 
- Individual salmon ENST counts are generated and converted to ENG counts
- The final PCA is generated using the combined salmon matrix

**Pull request merged**
